### ISSUE TITLE
Add Code Review page

### ISSUE THREAD

**Issue by kallewesterling** [dh-tech/dh-tech.github.io#56]
- [ ] Add a "Working Groups" section that this can live under
- [ ] Create a landing page for the Code Review Working Group under the "Working Groups" section
    - [ ] Add content: Information about the Working Group's aims
    - [ ] Add content: Links to existing resources with a sentence or two description
    - [ ] Add content: Contact information, "How you can get involved" and "Suggest more relevant resources"
- [ ] Provide links for the other resources we’re aware of that are relevant

**Comment by jdamerow** [comment]
We have a dedicated website for the working group now, that we should link to from the working group page.

**Comment by rlskoeser** [comment]
I think this was partially completed a while ago; I added the community code review link yesterday as part of the last updates for the website migration, so I'm going to call this done.
