### ISSUE TITLE
RSS feed?

### ISSUE THREAD

**Issue by quinnanya** [dh-tech/dh-tech.github.io#71]
Hi! I've been enjoying your meeting write-ups (especially the ones I couldn't quite manage to get out of bed for). Any chance you could add an RSS feed to the site?

**Comment by jdamerow** [comment]
That's a good idea! We'll look into it! Thanks for the suggestion :)

**Comment by quinnanya** [comment]
Thanks! Fingers crossed it should be pretty straightforward -- there's several tutorials & code snippets out there for RSS feeds on GitHub pages, e.g. [this one](https://gist.github.com/roachhd/f664d2cae2da899be3f6).

**Comment by rlskoeser** [comment]
@quinnanya thanks for this request and thanks for your patience. We finally finished the migration to switch over from Jekyll to Hugo, and this update includes RSS feeds. You can subscribe to specific subsections (news, blog) or to the main site feed for all updates. Please let us know if you have any follow-up questions or requests!
