### ISSUE TITLE
Migrate site from jekyll to hugo

### ISSUE THREAD

**Issue by rlskoeser** [dh-tech/dh-tech.github.io#77]
minimum for switchover:

- [x] import all latest content and update
- [x] tags (working but updates styles; use smallcaps/mixed case for readability & accessibility)
- [x] authors are not showing up on blog posts (single or list/summary); 
- [x] dates showing up on non-dated pages (about, SIG, etc); should only show up on blog, news, meetups
  - [x] fix date format for workshop/meetup posts (wrong format)
- [x] theming (? - how much do we care about current theme/colors? ) 
- [x] featured posts on the home page (what's new section; replicate pinned news items and pinned content pages) - use clarity's featured post functionality
- [x] handle news posts with permalinks: sc-changes, adho-sig, dhrse-whitepaper (redirect? or override url)
- [x] site search (minimal / parity with current site)
- [x] add "join us" link to main nav; highlight visually
- [x] disable time to read and social share (sitewide via config, if possible!)
- [x] add authors to RSS feeds
- [x] add links to make it easier to find RSS feeds (already included in html headers)
- [x] github action workflow to build and publish the site
- [x] clean up lingering jekyll content (`_layouts`, old md/html files)

## follow-up tasks
-  #79

**Comment by ColeDCrawford** [comment]
For Netlify/DecapCMS, do we need to use Netlify for deploys? Or are we thinking OnRender or GH Pages for prod? I think we need an OAuth server to use GH for auth, Netlify can do that but not sure how it would work with a different deploy strategy.

**Comment by rlskoeser** [comment]
@ColeDCrawford I was thinking we'd continue using github pages for the production site. I assume there's a way to make  that work with decap cms, since we were using some version of it before.

I was just using Render so there was a place to see the the WIP Hugo site.

We could continue Render to preview PRs if that's helpful.

**Comment by maltevogl** [comment]
two comments: 
third level headings at this side seems not to work: https://dh-tech.onrender.com/workshops/2022-02-17-lightning-talks/ 
add a link to the code review working group on the subpage of CodeReview WG

**Comment by rlskoeser** [comment]
migration complete!
